"""Add scheduling models

Revision ID: c6972f5a8ae
Revises: eb10d15465b3
Create Date: 2025-01-27 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa # noqa: F401
import sqlmodel # noqa: F401


# revision identifiers, used by Alembic.
revision: str = 'c6972f5a8ae'
down_revision: Union[str, None] = 'eb10d15465b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create CourseTypeEnum
    course_type_enum = sa.Enum('Lecture', 'Section', 'Lab', 'Tutorial', 'Seminar', name='coursetypeenum')
    course_type_enum.create(op.get_bind())
    
    # Create DayOfWeekEnum
    day_of_week_enum = sa.Enum('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', name='dayofweekenum')
    day_of_week_enum.create(op.get_bind())
    
    # Create schedule table
    op.create_table('schedule',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('is_locked', sa.Boolean(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('creation_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('update_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id')
    )
    
    # Create courseoffering table
    op.create_table('courseoffering',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('course_type', course_type_enum, nullable=False),
        sa.Column('lecturer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('course_id', sa.Integer(), nullable=False),
        sa.Column('org_id', sa.Integer(), nullable=False),
        sa.Column('creation_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('update_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create timeslot table
    op.create_table('timeslot',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('day_of_week', day_of_week_enum, nullable=False),
        sa.Column('start_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('end_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('course_offering_id', sa.Integer(), nullable=False),
        sa.Column('org_id', sa.Integer(), nullable=False),
        sa.Column('creation_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('update_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(['course_offering_id'], ['courseoffering.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create scheduledcourse table
    op.create_table('scheduledcourse',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('schedule_id', sa.Integer(), nullable=False),
        sa.Column('timeslot_id', sa.Integer(), nullable=False),
        sa.Column('org_id', sa.Integer(), nullable=False),
        sa.Column('creation_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('update_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['timeslot_id'], ['timeslot.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop tables in reverse order
    op.drop_table('scheduledcourse')
    op.drop_table('timeslot')
    op.drop_table('courseoffering')
    op.drop_table('schedule')
    
    # Drop enums
    sa.Enum(name='dayofweekenum').drop(op.get_bind())
    sa.Enum(name='coursetypeenum').drop(op.get_bind())
    
    # ### end Alembic commands ###
